# Generated by Django 3.0.8 on 2023-02-16 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin', models.CharField(max_length=200)),
                ('year', models.CharField(db_index=True, max_length=500)),
                ('make', models.CharField(db_index=True, max_length=500)),
                ('model', models.CharField(db_index=True, max_length=500)),
                ('trim', models.CharField(max_length=500)),
                ('dealer_name', models.CharField(max_length=500)),
                ('dealer_street', models.CharField(max_length=500)),
                ('dealer_city', models.CharField(max_length=500)),
                ('dealer_state', models.CharField(max_length=500)),
                ('dealer_zip', models.CharField(max_length=500)),
                ('listing_price', models.CharField(max_length=500)),
                ('listing_mileage', models.CharField(max_length=500)),
                ('used', models.CharField(max_length=500)),
                ('certified', models.CharField(max_length=500)),
                ('style', models.CharField(max_length=500)),
                ('driven_wheels', models.CharField(max_length=500)),
                ('engine', models.CharField(max_length=500)),
                ('fuel_type', models.CharField(max_length=500)),
                ('exterior_color', models.CharField(max_length=500)),
                ('seller_website', models.CharField(max_length=500)),
                ('first_seen_date', models.CharField(max_length=500)),
                ('last_seen_date', models.CharField(max_length=500)),
                ('dealer_vdp_last_seen_date', models.CharField(max_length=500)),
                ('listing_status', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'car_data',
                'managed': True,
            },
        ),
    ]
